### ISSUE TITLE
NPE on join

### ISSUE THREAD

**Issue by VinceOrlando** [runescapejon/CrazyFeet-Sponge#1]
`10.05 12:16:23 [Server] Server thread/ERROR [Sponge]: Could not pass ClientConnectionEvent$Join$Impl to Plugin{id=crazyfeetsponge, name=CrazyFeetSponge, version=1.4, description=CrazyFeet Ported over to Sponge, authors=[runescapejon], source=/mods/crazyfeet-sponge.jar}
10.05 12:16:23 [Server] INFO java.lang.NullPointerException
10.05 12:16:23 [Server] INFO at me.runescapejon.CrazyFeet.Listeners.CrazyFeetJoinListener.onCrazyFireJoin(CrazyFeetJoinListener.java:17) ~[CrazyFeetJoinListener.class:?]
10.05 12:16:23 [Server] INFO at org.spongepowered.common.event.listener.JoinListener_CrazyFeetJoinListener_onCrazyFireJoin113.handle(Unknown Source) ~[?:?]
10.05 12:16:23 [Server] INFO at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2281-5.2.0-BETA-2313]
10.05 12:16:23 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313) [SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2313]
10.05 12:16:23 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:297) [SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2313]
10.05 12:16:23 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338) [SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2313]
10.05 12:16:23 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) [SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2313]
10.05 12:16:23 [Server] INFO at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143) [SpongeImpl.class:1.10.2-2281-5.2.0-BETA-2313]
10.05 12:16:23 [Server] INFO at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:1621) [mp.class:?]
10.05 12:16:23 [Server] INFO at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:260) [NetworkDispatcher.class:?]
10.05 12:16:23 [Server] INFO at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73) [NetworkDispatcher.class:?]
10.05 12:16:23 [Server] INFO at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
10.05 12:16:23 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) [eo.class:?]
10.05 12:16:23 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
10.05 12:16:23 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
10.05 12:16:23 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
10.05 12:16:23 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
10.05 12:16:23 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
10.05 12:16:23 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]`

**Comment by runescapejon** [comment]
https://github.com/runescapejon/CrazyFeet-Sponge/releases
