### ISSUE TITLE
API 5 Support

### ISSUE THREAD

**Issue by GershonR** [runescapejon/CrazyFeet-Sponge#12]
I run a server on 1.10.2 Sponge, and I was wondering if you would support API 5.

**Comment by JoeSGT** [comment]
dude...
https://github.com/runescapejon/CrazyFeet-Sponge/releases
he has it `crazyfeet-sponge-Api5-1.1.1`
as you see it's API 5

**Comment by GershonR** [comment]
That says API71.1.1 the latest...

**Comment by GershonR** [comment]
Now I noticed it, sorry about that, nevermind
