### ISSUE TITLE
Helix's get more dense the more they are used

### ISSUE THREAD

**Issue by DrZoddiak** [runescapejon/CrazyFeet-Sponge#15]
If you use a helix trail, and keep turning it on and off again, the trail get more and More dense to the point where you can't see and eventually lag too much for it to be usable.

This appears to not only effect your trail, but also others trails as well.

**Comment by DrZoddiak** [comment]
I have also found that Globes are effected by this as well

**Comment by runescapejon** [comment]
I'll close this issue considering we talked on discord. Thanks for the pr.

**Comment by DrZoddiak** [comment]
Actually and unfortunately that pr doesnt fix this issue, I was unable to ascertain why, but I'm working toward it
